### ISSUE TITLE
Error running metrics.py

### ISSUE THREAD

**Issue by davidceka** [Anttwo/SuGaR#116]
Hi, I followed the instructions on the metrics part of the readme and created the json with {source_images_dir_path: vanilla_gaussian_splatting_checkpoint_path}

If i understood that right, the first part is the path to the images used to train the model, and the second part is the path to the vanilla gaussian splatting (the one i trained for 7000 iterations.
All good and well until the program crashes searching for the 30000 steps checkpoint:
`Loading Vanilla 3DGS model config outputs/sanginesio/...                                                                Found image extension .jpg                                                                                              Traceback (most recent call last):                                                                                        File "/home/vrai/repos/SuGaR/metrics.py", line 166, in <module>                                                           nerfmodel_30k = GaussianSplattingWrapper(                                                                             File "/home/vrai/repos/SuGaR/sugar_scene/gs_model.py", line 139, in __init__                                              self.gaussians.load_ply(                                                                                              File "/home/vrai/repos/SuGaR/gaussian_splatting/scene/gaussian_model.py", line 216, in load_ply                           plydata = PlyData.read(path)                                                                                          File "/root/anaconda3/envs/sugar/lib/python3.9/site-packages/plyfile.py", line 401, in read                               (must_close, stream) = _open_stream(stream, 'read')                                                                   File "/root/anaconda3/envs/sugar/lib/python3.9/site-packages/plyfile.py", line 481, in _open_stream                       return (True, open(stream, read_or_write[0] + 'b'))                                                                 FileNotFoundError: [Errno 2] No such file or directory: 'outputs/sanginesio/point_cloud/iteration_30000/point_cloud.ply'`

do you have any clue as to why?

**Comment by VictorStarkSnow** [comment]
The same issue. I found that there is no iteration_30000/point_cloud.ply according to the default setting of training 7000 iterations of vanilla GS. A litter trick is you can change metrics.py:169 from iteration_to_load=30000 to iteration_to_load=7000 avoid this problem if you only want to evalue the SuGar not with Vanila. Or you can train 30000 iterations of vanilla GS.

**Comment by davidceka** [comment]
> The same issue. I found that there is no iteration_30000/point_cloud.ply according to the default setting of training 7000 iterations of vanilla GS. A litter trick is you can change metrics.py:169 from iteration_to_load=30000 to iteration_to_load=7000 avoid this problem if you only want to evalue the SuGar not with Vanila. Or you can train 30000 iterations of vanilla GS.

Yes, hardcoding that works also. I solved by training the initial vanilla model for 30000 iterations (I suggest trying it for more accurate metrics)
Still signaling about this to the developers.

**Comment by CHenYYff** [comment]
I created a similar .json with the content {"./data/bicycle/":"./output/"}. But I encountered the following error when running it.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
File "/media/jinshan/data/cys/SuGaR/metrics.py", line 344, in <module>
refined_sugar = SuGaR(
File "/media/jinshan/data/cys/SuGaR/sugar_scene/sugar_model.py", line 329, in __init__
scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous
My running command is python metrics.py --scene_config ./output/camerasss.json -r "density" , do you know what the reason is? How is your .json file setting? Thank you.

**Comment by fsr-cell** [comment]
> I created a similar .json with the content {"./data/bicycle/":"./output/"}. But I encountered the following error when running it.我创建了一个类似的.json，内容为{“./data/bicycle/”：“./output/”}。但我运行时遇到了以下错误。 Binding radiance cloud to surface mesh...将辐射云绑定到表面网格...... Traceback (most recent call last):追溯（最近一次通话）： File "/media/jinshan/data/cys/SuGaR/metrics.py", line 344, in 文件“/media/jinshan/data/cys/SuGaR/metrics.py”，第 344 行，在 refined_sugar = SuGaR(  refined_sugar = SuGaR（ File "/media/jinshan/data/cys/SuGaR/sugar_scene/sugar_model.py", line 329, in **init**文件“/media/jinshan/data/cys/SuGaR/sugar_scene/sugar_model.py”，第 329 行，** 初始化** scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)scales = scales.clamp_min（0.0000001）.reshape（len（faces_verts）， -1， 1）.expand（-1， self.n_gaussians_per_surface_triangle， 2）.clone（）.reshape（-1， 2） RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguousRuntimeError：无法将 0 元素的张量重塑为[0， -1， 1]，因为未指定的维度大小-1 可以是任意值且存在歧义 My running command is python metrics.py --scene_config ./output/camerasss.json -r "density" , do you know what the reason is? How is your .json file setting? Thank you.我的运行命令是 python metrics.py --scene_config ./output/camerasss.json -r “density”，你知道原因是什么吗？你的.json 文件设置怎么样？谢谢。

The program might not be finding the required .ply file because it's not in the correct directory. My .ply file was in `/output/coarse_mesh/playroom`, but the program was looking for it directly in `/output/coarse_mesh/`.  Moving the .ply file directly to `/output/coarse_mesh/` solved the problem.
