### ISSUE TITLE
Should I go with a normal callmap for my current dataset?

### ISSUE THREAD

**Issue by hanjoonwon** [Anttwo/SuGaR#125]
I'm wondering if it's not currently processed with nerfstudio or anything like that

**Comment by Anttwo** [comment]
Hey @hanjoonwon,

Just like the original implementation of Gaussian Splatting, the code needs undistorted images following a pinhole model.
COLMAP is indeed a straightforward tool to produce such inputs; I recommend trying SuGaR with COLMAP first.

**Comment by hanjoonwon** [comment]
> Hey @hanjoonwon,
> 
> Just like the original implementation of Gaussian Splatting, the code needs undistorted images following a pinhole model. COLMAP is indeed a straightforward tool to produce such inputs; I recommend trying SuGaR with COLMAP first.

thank you for nice answer
