### ISSUE TITLE
Can the viewer see the 3D rendering converge in real time? like instant ngp

### ISSUE THREAD

**Issue by hanjoonwon** [Anttwo/SuGaR#129]
I'm wondering if it's possible to watch the process of 3d rendering in real time. According to the readme, I've already checked the viewer to watch the file that has completed the train, but I'm wondering if it's possible to watch it at the same time as the train like instant ngp and original repo

**Comment by hanjoonwon** [comment]
follwing https://github.com/Anttwo/SuGaR/issues/92

deactivate conda solve problem

**Comment by Anttwo** [comment]
Hello @hanjoonwon,

Sadly, there is currently no option to watch the model train in real-time. The viewer only allows you to see the result after training.
I'm sorry for that.

I suppose it could be possible to make a viewer like Instant-NGP; It’s just that it would require a lot of effort from me hehe 😄 

I agree it would be a (very) useful feature, though. I will definitely keep that in mind.

**Comment by hanjoonwon** [comment]
> Hello @hanjoonwon,
> 
> Sadly, there is currently no option to watch the model train in real-time. The viewer only allows you to see the result after training. I'm sorry for that.
> 
> I suppose it could be possible to make a viewer like Instant-NGP; It’s just that it would require a lot of effort from me hehe 😄
> 
> I agree it would be a (very) useful feature, though. I will definitely keep that in mind.

Thanks  :)  😄
