### ISSUE TITLE
where is the variable vertices_density_quantile?

### ISSUE THREAD

**Issue by cmh1027** [Anttwo/SuGaR#167]
![image](https://github.com/Anttwo/SuGaR/assets/22341329/8ce69ac1-eb93-48c2-9c67-1d47521bf1e1)
According to README, vertices_density_quantile should be next to poisson_depth. Was there any update for this code?

**Comment by Anttwo** [comment]
Hello @cmh1027,

Indeed, there was an update for the code a few weeks ago!
Here is the variable you are looking for:
https://github.com/Anttwo/SuGaR/blob/9c059ac9754a7bc058c17788181310376bd7981f/sugar_extractors/coarse_mesh.py#L43

Everything should work fine if you pull the last version of the code.
