### ISSUE TITLE
CUDA mismatch error while installing in docker. 

### ISSUE THREAD

**Issue by jaswin90** [Anttwo/SuGaR#183]
After doing in the .yml file installations, once we try to install the setup.py for simple-knn and diff-gaussian-rasterization, it is throwing a cuda mismatch error as nvcc is pointing to the base  docker and pytorch is compiled with a different cuda.

**Comment by jaswin90** [comment]
please reopen if it doesn't work.

**Comment by ZachariVaia** [comment]
Hello could you send the docker image?

**Comment by ZachariVaia** [comment]
> please reopen if it doesn't work.

Hello could you send the docker image?
