### ISSUE TITLE
train_full_pipeline.py: error: unrecognized arguments: --export_obj True

### ISSUE THREAD

**Issue by Narumi-Maria** [Anttwo/SuGaR#213]

**Comment by wwtj08** [comment]
i met the same problem.

**Comment by Anttwo** [comment]
Oops sorry, this was a dumb error from me!
This argument was previously named "--export_uv_textured_mesh' but I renamed it into "--export_obj" for simplicity, and to make the code consistent with the recent Gaussian Frosting project.

But I actually forgot to rename the argument as "--export_obj" in the training script haha!
It is fixed now, I just pushed the change.
