### ISSUE TITLE
COLMAP dataset

### ISSUE THREAD

**Issue by Iron486** [Anttwo/SuGaR#224]
Hi!

I am running the following command to train from scratch: python train_full_pipeline.py -s person-hall  -r density--high_poly True --export_obj True 

where `person-hall` is one of the COLMAP datasets downloaded from [here](https://colmap.github.io/datasets.html ). The problem now is that I get these errors:

```
Optimizing output/vanilla_gs/person-hall/
Output folder: output/vanilla_gs/person-hall/ [29/10 13:35:57]
/home/farchid/research/SuGaR/person-hall/sparse/0/images.txt [29/10 13:35:57]
Traceback (most recent call last):
  File "/home/farchid/research/SuGaR/gaussian_splatting/scene/dataset_readers.py", line 136, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "/home/farchid/research/SuGaR/gaussian_splatting/scene/colmap_loader.py", line 187, in read_extrinsics_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/farchid/research/SuGaR/person-hall/sparse/0/images.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farchid/research/SuGaR/./gaussian_splatting/train.py", line 220, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/farchid/research/SuGaR/./gaussian_splatting/train.py", line 36, in training
    scene = Scene(dataset, gaussians)
  File "/home/farchid/research/SuGaR/gaussian_splatting/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/farchid/research/SuGaR/gaussian_splatting/scene/dataset_readers.py", line 141, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
  File "/home/farchid/research/SuGaR/gaussian_splatting/scene/colmap_loader.py", line 251, in read_extrinsics_text
    with open(path, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/farchid/research/SuGaR/person-hall/sparse/0/images.txt'
```

and this:

```
Traceback (most recent call last):
  File "/home/farchid/research/SuGaR/train.py", line 131, in <module>
    coarse_sugar_path = coarse_training_with_density_regularization(coarse_args)
  File "/home/farchid/research/SuGaR/sugar_trainers/coarse_density.py", line 289, in coarse_training_with_density_regularization
    nerfmodel = GaussianSplattingWrapper(
  File "/home/farchid/research/SuGaR/sugar_scene/gs_model.py", line 132, in __init__
    cam_list = load_gs_cameras(
  File "/home/farchid/research/SuGaR/sugar_scene/cameras.py", line 34, in load_gs_cameras
    with open(gs_output_path + 'cameras.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/vanilla_gs/person-hall/cameras.json'
```

How can I solve this issue? I don't know why it does not find the files if they come from the original COLMAP datasets.

Thank you!

**Comment by Iron486** [comment]
I solved the issue installing the COLMAP library and following the instruction on the COLMAP website to reconstruct the 3d scene from the datasets.

**Comment by KleinXin** [comment]
> I solved the issue installing the COLMAP library and following the instruction on the COLMAP website to reconstruct the 3d scene from the datasets.

I have the same problem. Could you please share the output files of COLMAP？
or names of all those files
thx

**Comment by Iron486** [comment]
The problem that I encountered was that the output files should follow the COLMAP scheme which is like this:

+── images
│   +── image1.jpg
│   +── image2.jpg
│   +── ...
+── sparse
│   +── 0
│   │   +── cameras.bin
│   │   +── images.bin
│   │   +── points3D.bin
│   +── ...
+── dense
│   +── 0
│   │   +── images
│   │   +── sparse
│   │   +── stereo
│   │   +── fused.ply
│   │   +── meshed-poisson.ply
│   │   +── meshed-delaunay.ply
│   +── ...
+── database.db

If you give one of the [datasets](https://colmap.github.io/datasets.html) as input to COLMAP, and follow the instruction [here](https://colmap.github.io/tutorial.html) you can obtain the outputs to give as input to SuGaR in the right format.

I hope I was clear :)

**Comment by KleinXin** [comment]
> The problem that I encountered was that the output files should follow the COLMAP scheme which is like this:
> 
> +── images │ +── image1.jpg │ +── image2.jpg │ +── ... +── sparse │ +── 0 │ │ +── cameras.bin │ │ +── images.bin │ │ +── points3D.bin │ +── ... +── dense │ +── 0 │ │ +── images │ │ +── sparse │ │ +── stereo │ │ +── fused.ply │ │ +── meshed-poisson.ply │ │ +── meshed-delaunay.ply │ +── ... +── database.db
> 
> If you give one of the [datasets](https://colmap.github.io/datasets.html) as input to COLMAP, and follow the instruction [here](https://colmap.github.io/tutorial.html) you can obtain the outputs to give as input to SuGaR in the right format.
> 
> I hope I was clear :)

thx，problem already solved
