### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by sidoniepc** [Anttwo/SuGaR#234]
I am using dataset for gs, but it keeps saying  No such file or directory: 'output\\vanilla_gs\\garden\\cameras.json', and I also couldn't find camera.json in gs dataset. What is the problem?

**Comment by sidoniepc** [comment]
I follow the steps making dataset in gaussian-splatting, but still get this problem.

**Comment by sidoniepc** [comment]
so if you are running on Windows, remember to add "set" in the line 122 in train_full_pipeline.py.
<img width="558" alt="企业微信截图_17351754524358" src="https://github.com/user-attachments/assets/a7fac597-2f46-4b9b-a83e-4cddc700ddac" />

**Comment by RusticWolf86** [comment]
I am facing this issue again and again - I am using Ubuntu 22.04 as WSL from win11.
can you please help me
