### ISSUE TITLE
Question about entropy loss

### ISSUE THREAD

**Issue by dhdkc** [Anttwo/SuGaR#4]
Hi, it's really exciting to see this awesome work!

I have a question about the entropy loss in the paper. How do you calculate the entropy loss, as there are no groud truth density provided?

**Comment by Anttwo** [comment]
It is exactly as Antarashtriya said!
In practice, we compute this loss only for the Gaussians located in the field of view of the current camera (during a training iteration).

Best!

**Comment by dhdkc** [comment]
Thanks for your detailed explanation, now I've understand.
