### ISSUE TITLE
I am using Windows 10 and have some issues

### ISSUE THREAD

**Issue by kitmallet** [Anttwo/SuGaR#46]
@Anttwo 
Hello Antoine!
I am using Windows 10 and I know of the issues with path (/ and \) with the differences between Linux and Windows conventions.
Do you foresee having those changes made soon or would you suggest that I use a different operating system in the meantime, meaning Ubuntu?

**Also have:**
128 GB Ram
RTX 3060 12 GB

The RTX 3060 is a hindrance as I have so many Photogrammetry models I have amassed over the years that I would love to use. Some of which are well over 750 photos.
With my setup, I am limited to under 75 since the train.py takes an enormous amount of time with these limitations. What do you suggest as a minimum GPU for the use of up to and over 1000 photos perhaps up to 2000?

Here is my progress so far for all to see as I am sure many people are having the same problem:

**Test run dec21 2023**

**CONVERT**

(sugar) C:\Users\conan\SuGaR>python gaussian_splatting/convert.py -s data/bullet_01

....Undistorting image [50/50]
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.034 [minutes]
Done.

**TRAIN**

(sugar) C:\Users\conan\SuGaR>python gaussian_splatting/train.py -s data/bullet_01 -m output/bullet_01 --iterations 30000 --save_iterations 7000 30000 --checkpoint_iterations 7000 30000

...[ITER 30000] Evaluating train: L1 0.013728742301464082 PSNR 33.831542587280275 [21/12 11:57:32]

[ITER 30000] Saving Gaussians [21/12 11:57:32]

[ITER 30000] Saving Checkpoint [21/12 11:57:55]

Training complete. [21/12 11:57:59]

**OPTIMIZE**

(sugar) C:\Users\conan\SuGaR>python train.py -s data/bullet_01 -c output/bullet_01/ -r "density"

...Loading mesh to bind to:
./output/coarse_mesh\bullet_01\sugarmesh_coarse\bullet_01\3Dgs7000_densityestim02_sdfnorm02_level03_decim1000000.ply...
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\bullet_01\sugarmesh_coarse\bullet_01\3Dgs7000_densityestim02_sdfnorm02_level03_decim1000000.ply
Mesh to bind to loaded.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "C:\Users\conan\SuGaR\train.py", line 160, in <module>
    refined_sugar_path = refined_training(refined_args)
  File "C:\Users\conan\SuGaR\sugar_trainers\refine.py", line 393, in refined_training
    sugar = SuGaR(
  File "C:\Users\conan\SuGaR\sugar_scene\sugar_model.py", line 322, in __init__
    scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

Thanks for your work!

**Comment by yuedajiong** [comment]
Hi, 
    Please check and modify these code:   .split('/')  in coarse_mesh.py
    If you need a token, please use: os.sep

**Comment by nehilsood** [comment]
Hi @yuedajiong @Anttwo 
actually the patch for both windows and linux system is using os.path.normpath(os.path.join( or pathlib[best I suggest]
or any other
