### ISSUE TITLE
videos requirements

### ISSUE THREAD

**Issue by oym050922021** [Anttwo/SuGaR#61]
hello, 
thank you for the source code. When training the model, are there any requirements for the video, such as image resolution, shooting speed, shooting Angle, shooting trajectory, minimum and maximum number of video frames, whether the first frame and the last frame should be consistent, etc. Thank you !

**Comment by Anttwo** [comment]
Hello @oym050922021,

In theory, there is no particular requirement on the video to run the code, but in practice, here are some tips to get good-looking reconstructions:
1. The code is able to process any image resolution, but of course it is better to aim for HD resolution (such as 1080x1920)
2. There is no requirement on shooting speed, as long as you manage to avoid motion blur (and any kind of blur in general)
3. Concerning shooting angle/trajectory, it depends on what you want. If you want the mesh to be really close to the real surface, then you might need to capture photos from various angles (for instance, a 360° capture of an object works well). If your images cover only one side of an object, then the reconstructed mesh might have some border artifacts on the frontier between the "seen area" and the "unseen area". However, the hybrid representation (mesh + Gaussians) generally looks good, even for objects covered only from one side.
4. As explained in the README.md file, in our experiments, we use between 150 and 300 images depending on the scene (this is a standard number of NeRFs). You are free to downsample the video to reduce the number of images. If you want to reconstruct bigger scenes and you need more images, it should be possible (but it might require more memory).
5. There is no need to make the first and last frames consistent.

I hope my answers will be useful! Feel free to ask additional questions!

**Comment by oym050922021** [comment]
@Anttwo ok, thank you for your reply.
