### ISSUE TITLE
 extract_mesh？

### ISSUE THREAD

**Issue by nangongliufeng** [Anttwo/SuGaR#67]
This problem occurs when extracting mesh, what is the reason?
Found image extension .png
Vanilla 3DGS Loaded.
48 training images detected.
The model has been trained for 7000 steps.
2.414474 M gaussians detected.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "/root/SuGaR/train.py", line 181, in <module>
    refined_mesh_path = extract_mesh_and_texture_from_refined_sugar(refined_mesh_args)
  File "/root/SuGaR/sugar_extractors/refined_mesh.py", line 122, in extract_mesh_and_texture_from_refined_sugar
    refined_sugar.load_state_dict(checkpoint['state_dict'])
  File "/root/miniconda3/envs/sugar/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SuGaR:
        size mismatch for _surface_mesh_faces: copying a param with shape torch.Size([1996692, 3]) from checkpoint, the shape in current model is torch.Size([1997015, 3]).
        size mismatch for _points: copying a param with shape torch.Size([1034486, 3]) from checkpoint, the shape in current model is torch.Size([1034834, 3]).
        size mismatch for all_densities: copying a param with shape torch.Size([1996692, 1]) from checkpoint, the shape in current model is torch.Size([1997015, 1]).
        size mismatch for _scales: copying a param with shape torch.Size([1996692, 2]) from checkpoint, the shape in current model is torch.Size([1997015, 2]).
        size mismatch for _quaternions: copying a param with shape torch.Size([1996692, 2]) from checkpoint, the shape in current model is torch.Size([1997015, 2]).
        size mismatch for _sh_coordinates_dc: copying a param with shape torch.Size([1996692, 1, 3]) from checkpoint, the shape in current model is torch.Size([1997015, 1, 3]).
        size mismatch for _sh_coordinates_rest: copying a param with shape torch.Size([1996692, 15, 3]) from checkpoint, the shape in current model is torch.Size([1997015, 15, 3]).

**Comment by danperazzo** [comment]
I have the same problem, what did you do to solve it please?

**Comment by nangongliufeng** [comment]
> I have the same problem, what did you do to solve it please?

This problem may be that the model parameters are different. Run train_coarse_sdf.py first, and then extract_mesh.py
