### ISSUE TITLE
Why use abs() for sdf_estimation

### ISSUE THREAD

**Issue by zParquet** [Anttwo/SuGaR#68]
I noticed this line
https://github.com/Anttwo/SuGaR/blob/5ddbe7ec4211e3fb5b2b666b81c2d96aaf729466/sugar_trainers/coarse_sdf.py#L655
, where `sdf_values` represents the calculated sdf of the 3D points (Eq.6 in the paper), and `sdf_estimation` represents the difference between projection depth and depth-map depth. However, I don't know why `sdf_estimation` here needs `abs()`? Is it a mistake?

Thanks!

**Comment by Anttwo** [comment]
Hello @zParquet,

Indeed, we want the Gaussians to align with the zero-level set of this *"ideal"* SDF function. 

It is not possible to compute easily the sign of the SDF in practice, as it is very difficult to know if a point is located inside or outside an object during optimization. 
However, we do not care about the sign, as we just want the zero-level sets of both (a) the SDF estimator and (b) the ideal SDF to align (in other words, we want `sdf_values` and `sdf_estimation` to have the same zero points). 
Therefore, we just optimize on the absolute value : it makes computation easier and does not alter the convergence of the zero-level sets.

I hope this message helps you!

**Comment by zParquet** [comment]
I understand. Thank you for your prompt and thoughtful response!
