### ISSUE TITLE
How to visualize the trained results

### ISSUE THREAD

**Issue by WN-Wolf** [Anttwo/SuGaR#74]
Here are some outputs, but I don't know how to visualize the results. 
Please give me some suggestions, thanks!

Saving model...
Model saved.
Training finished after 15000 iterations with loss=0.028884241357445717.
Saving final model...
Final model saved.
==================================================
Starting extracting texture from refined SuGaR model:
Scene path: ./dataset/db/drjohnson
Iteration to load: 7000
Vanilla 3DGS checkpoint path: ./output/4b0d4b34-1/
Refined model path:
./output/refined/drjohnson/sugarfine_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000_normalconsistency01_gaussperface
1/15000.pt
Coarse mesh path: ./output/coarse_mesh/drjohnson/sugarmesh_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply
Mesh output directory: ./output/refined_mesh/drjohnson
Mesh save path:
./output/refined_mesh/drjohnson/sugarfine_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000_normalconsistency01_gausspe
rface1.obj
Number of gaussians per surface triangle: 1
Square size: 10
Postprocess mesh: False
==================================================
Source path: ./dataset/db/drjohnson
Gaussian splatting checkpoint path: ./output/4b0d4b34-1/

Loading Vanilla 3DGS model config ./output/4b0d4b34-1/...
Found image extension .jpg
Vanilla 3DGS Loaded.
230 training images detected.
The model has been trained for 7000 steps.
1.787029 M gaussians detected.
Binding radiance cloud to surface mesh...
Texture extracted.
Texture shape:
torch.Size([7100, 7100, 3])
Saving textured mesh...
Texture saved at:
./output/refined_mesh/drjohnson/sugarfine_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000_normalconsistency01_gausspe
rface1.obj

**Comment by Anttwo** [comment]
Hello @WN-Wolf,

To visualize the results, you can use the notebook `view_sugar_results.ipynb`. The notebbok shows how to render images using the hybrid representations. It also lets you render images of the mesh with a traditional texture.

However, I admit the notebook is not very convenient as it only lets you render images one by one.
**I'm currently working on a dedicated viewer to visualize and navigate in real-time in the reconstructed scene.**

In the meantime, if you want to visualize the mesh in real-time (but not the hybrid representation mesh+Gaussians), you can open the output mesh (_i.e._ the `.obj` file) in a traditional 3D software like [Blender](https://www.blender.org/).

I hope this message helps you!

**Comment by WN-Wolf** [comment]
Hello @Anttwo,
Thanks for you help, now I get 3D result by Blender.  I'm very excited to present the results.
![渲染图片](https://github.com/Anttwo/SuGaR/assets/75304226/bd5d2139-a797-4d49-95d6-cd734e8ccc06)

I want to build my own dataset. I still have some questions. 
First, what type of camera should I use? Do you have any recommendations?
Next, how do I parse data? Like the below struct, how to get  cameras.bin &&  images.bin &&  points3D.bin &&  points3D.ply &&  project.ini files?
Thank you again, and looking forward to your reply!
![struct1](https://github.com/Anttwo/SuGaR/assets/75304226/9b0c30ab-aff7-459f-ae34-abebb87ede14)
![struct2](https://github.com/Anttwo/SuGaR/assets/75304226/d3486da8-c8b3-4d12-bf92-737a8e48d40f)

**Comment by Anttwo** [comment]
Hello @WN-Wolf,

The short answer is: Your custom dataset should have the exact same structure as datasets used for running the vanilla 3D Gaussian Splatting code hehe!

Please refer to their original README.md file for more details.
But yes, it is more or less the structure you mentioned: Their `convert.py` script, which is included in SuGaR's code, should generate the right structure (with `bin` files, etc.) from your images.
All you have to do is putting all your images inside a subfolder called "input", and the `convert.py` script will generate the `images` folder, the `sparse` folder and everything you need.

Concerning tools for visualizing the results, **I've just added a dedicated viewer for SuGaR!** The viewer lets you navigate inside your reconstructed scene, and you can switch between the different representations (the hybrid representation, the mesh textured with a traditional UV texture, and the wireframe mesh). 
Feel free to check this out!
