### ISSUE TITLE
Out of Memory: I changed the code to solve the issue, but I'm not sure whether it is reasonable

### ISSUE THREAD

**Issue by ygtxr1997** [Anttwo/SuGaR#82]
On a large scene, with >1200 images as input, I met OOM issue.
And I made the following modifications:
1. In `sugar_scene/cameras.py`:
![image](https://github.com/Anttwo/SuGaR/assets/22703453/d829ae19-1dc3-4bfc-a64b-0325f180695c)
2. In `sugar_trainers/coarse_sdf.py` and `sugar_trainers/refine.py`:
![image](https://github.com/Anttwo/SuGaR/assets/22703453/2d589106-3900-4014-9d0b-a429fc2428e2)

The OOM problem doesn't occur anymore and the training process is ok.

---------------------------------------------------

I'm not sure whether I did the right thing?

**Comment by Anttwo** [comment]
Hello @ygtxr1997,

In theory, this should not change the results.
Actually, a lot of people use the `data_device='cpu'` trick in the original Gaussian Splatting implementation to make the code work with much larger datasets.

I suppose it slows down the optimization process, but I have not tried it myself.
I should definitely investigate the speed performance for this.

But don't worry, in theory, it should be ok!
And thank you for your message; I should add it to the `README.md` file, as it could help people working with larger datasets.
