### ISSUE TITLE
The real-time viewer failed to run (resolved)

### ISSUE THREAD

**Issue by bendanpuppy** [Anttwo/SuGaR#88]
l click the link to open the viewer in my browser, but the content is blank. l use the linux system. Dose anyone have the same problem as me? how do you solve it?
l tried to change Firefox to Google browser, but it didn't work.
![37](https://github.com/Anttwo/SuGaR/assets/148044175/01079485-6333-46b1-a8c2-e1f8b31c904b)

**Comment by Anttwo** [comment]
Hello @bendanpuppy,

Alright, let's investigate!

May I ask:
1. What does your `./output` folder look like?
2. What command did you enter to run the viewer? Did you use a relative or absolute path in `python run_viewer.py -p <path to the refined ply file>`?
3. Could you press `F12` in Firefox when running the viewer, to open the Firefox Developer Tools? You should see some details concerning the error you browser encountered.

I see that the main text (top left corner) is a little too large and gets on the icons in the top right corner of the screen. Thank you for showing me this hehe, I did not have this problem in my WSL2 installation, so it's good to know that it can happen, as it can help me improve the aesthetic of the viewer.

Looking forward to your reply!

**Comment by bendanpuppy** [comment]
Thank you very much for your reply!
The following is the answer to the question:
1.my `./output` folder look like this `~/SuGaR/output/refined_ply/hole1/sugarfine_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000_normalconsistency01_gaussperface1.ply`.
2.I used a absolute path in command.
3.when I press F12 in Firefox, it indicates that the path is incorrect, so I use a relative path and follow the prompts to delete`/`, like this `python run_viewer.py -p output/refined_ply/hole1/sugarfine_3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000_normalconsistency01_gaussperface1.ply`, and then my problem is solved!
![1](https://github.com/Anttwo/SuGaR/assets/148044175/62ae7594-e930-49e1-8877-ecfef1853cae)
![2](https://github.com/Anttwo/SuGaR/assets/148044175/e16bec67-6a46-4c65-9b85-0c70e602c43a)
