### ISSUE TITLE
bad results for a simple scene

### ISSUE THREAD

**Issue by chenin-wang** [Anttwo/SuGaR#98]
I have captured 1000 photos using a RealSense camera and performed reconstruction with default parameters, but the results are not satisfactory. Could you provide some suggestions about parameters for adjustments? @Anttwo 
![image](https://github.com/Anttwo/SuGaR/assets/88609203/a305eae8-3c3d-4f67-8b26-44be2a999696)
![image](https://github.com/Anttwo/SuGaR/assets/88609203/b78402d0-990a-4be9-a95d-c9ce2f0ff0c4)

**Comment by Anttwo** [comment]
Hello @chenin-wang,

Indeed, the results look very bad, SuGaR should not return something like that.
At first glance, this scene typically looks like the kind of scenes SuGaR handles very well, so I think we should definitely be able to get good results.

Let's investigate!

May I ask the following questions:
1. Did you perform a 360 trajectory around your object, with your camera? Or does your capture cover only one side of the object?
2. Did you use the `convert.py` script to generate initial data before applying vanilla Gaussian Splatting?
3. Is there a lot of motion blur in your video?

**Comment by chenin-wang** [comment]
Thank you for your response. 

I captured multiple rounds of images and used the pipeline you mentioned in the readme. Firstly, I used colmap by convert.py, then applied vanilla Gaussian Splatting, and finally used SUGAR. Regarding your third question, I have checked most of the photos, and there is no motion blur present. 

Additionally, I have uploaded my photos.pls check it.

[JPEGImages.zip](https://github.com/Anttwo/SuGaR/files/13971359/JPEGImages.zip)
[JPEGImages1.zip](https://github.com/Anttwo/SuGaR/files/13971360/JPEGImages1.zip)
[JPEGImages2.zip](https://github.com/Anttwo/SuGaR/files/13971361/JPEGImages2.zip)
[JPEGImages3.zip](https://github.com/Anttwo/SuGaR/files/13971363/JPEGImages3.zip)

**Comment by chenin-wang** [comment]
Since I have knowledge of the camera's intrinsic parameters, I am wondering if modifying the camera type in the convert.py script and using the known intrinsic parameters would be helpful for me. Next, I will experiment with it.@Anttwo

**Comment by chenin-wang** [comment]
The main objects I captured have symmetry, which could also affect the results.

**Comment by yuedajiong** [comment]
用”维达“纸的哈，中国朋友。
你这对象好像没啥对称性。

**Comment by chenin-wang** [comment]
> 纸的哈，中国朋友。 你这对象好像没啥对称性。 你的纹理也比较丰富，也应该方便colmap找特征定位。
> 
> 我应该算小有经验，如何把一个场景/对象搞的还行。 一个提示：现在很多场景/对象，构造不好，其实在colmap这一步，出来的camera pose就不是那么精准。
> 
> camera pose其实对后面算法影响很大。 你看GS算法，camera pose都不是经过什么NN网络，直接到了render里面，参与硬算。 硬算意味着要求很准才行，没很强容忍误差的能力。
> 
> 我扫了一下你的图片，由于你的图片不是0补齐等长的文件名，所以不能简单的直接next来观察轨迹。 我抽样了一部分，我的建议： 如果你要拍照那个”维达“的为中心，你可以很微小的移动，绕完一周。比如360度，你搞个180张以上，运动的轨迹比比较稳一点，平滑一点。 （还是想说，那个pose的精度很重要。GS几乎是没有NN网络，几乎是个暴力拟合的硬算法，所以嘛，是优势，也是劣势。）

Hello! Thank you for your advices. 
Although the photo names were not completed, they were captured in sequential order. Sorting them by name would allow for trajectory verification. When I mentioned symmetry, I was referring to the symmetric texture patterns on both sides of the cardboard box.

My capture strategy involved fixing the camera and rotating the target object for 2-3 rounds, resulting in 1000 photos. I checked the camera poses computed by colmap, as shown in the image below, and it is clearly incorrect. It seems that I may need to adjust my capture approach.
![image](https://github.com/Anttwo/SuGaR/assets/88609203/2f5318f7-e49d-4607-8b2e-f19cc6d3cb20)

**Comment by WN-Wolf** [comment]
@chenin-wang @yuedajiong 我很好奇，Who is truly an international friend? Haha

**Comment by chenin-wang** [comment]
@WN-Wolf 我是中国人, Technology has no walls. 😄

**Comment by kitmallet** [comment]
@chenin-wang I posted a new issue talking about what you need to do to correct your dataset. I hope this helps out!
Good luck,
Kit

**Comment by yuedajiong** [comment]
@WN-Wolf  我也是中国人。
@chenin-wang  1）你要不先用一个3D的合成对象（有ob文件j的），你先render一下（这种有精确的camera pose)，然后你确保你的这些流程参数没有问题。我可以给你代码，数据一两分钟，训练十来二是分钟。  2）你再采集比较高质量的真实的。 （我在issue的发的消息可以看到，我就是拼多多买了一个直播的那种tunetable)，把手机固定住，然后采集一圈。这种构造就比较好一些。   3）然后你再弄你的算法。如果你弄mask含mask损失，你可以参考：https://github.com/fudan-zvg/4d-gaussian-splatting

**Comment by yuedajiong** [comment]
@Anttwo    2d mask for 3d gs:   https://github.com/fudan-zvg/4d-gaussian-splatting

**Comment by chenin-wang** [comment]
@yuedajiong 非常感谢！我会试一下。@kitmallet #102 These tips are useful.

**Comment by yuedajiong** [comment]
@chenin-wang 
1. 用上面程序，对某个obj产生图片。
2. 用这个脚本一步一步执行，产生comap的，参数我调试过。
3. sugar训练，喝大杯咖啡，坐等好结果。
[0.txt](https://github.com/Anttwo/SuGaR/files/13984355/0.txt)

**Comment by chenin-wang** [comment]
👍👍

![CoffeeCoffeeCupGIF](https://github.com/Anttwo/SuGaR/assets/88609203/51fa6967-807c-4b2f-a562-5c7f72652446)
